### ISSUE TITLE
Demo offline?

### ISSUE THREAD

**Issue by RuairiSpain** [xxczaki/omdb-graphql-wrapper#2]
Is the demo GraphQL server offline?  I can't reach the endpoint.

Great example of GQL.

**Comment by xxczaki** [comment]
Hi, is turns out that the usage limit of my API key (which I used for the demo page) has been exceded. I will try to obtain another API key soon, so that others will be able to play with it ;)

**Comment by xxczaki** [comment]
@RuairiSpain Demo is now working again!
